version: 2.1
jobs:
   build:
    docker:
    - image: circleci/elixir:1.8.2
      environment:
        MIX_ENV: test

    steps:
    - checkout

    - run: mix local.hex --force
    - run: mix local.rebar --force

    - restore_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
    - run: mix do deps.get, deps.compile
    - save_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
        paths:
            - deps
            - ~/.mix
            - _build

    - run: mix compile
    - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
    - restore_cache:
        keys:
            - plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}

  tests:
    docker:
    - image: circleci/elixir:1.8.2

    steps:
    - checkout
    - restore_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
    - run: mix test
    - run: 
        command: MIX_ENV=test mix coveralls.circle
        environment:
          COVERALLS_REPO_TOKEN: ${COVERALLS_TOKEN}

  format_check:
    docker:
    - image: circleci/elixir:1.8.2
      environment:
        MIX_ENV: test
    steps:
    - checkout
    - run: mix format --check-formatted

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - format_check
        requires:
            - build
    - tests:
        requires:
            - build